### ISSUE TITLE
음성 검열 String Matching 추가

### ISSUE THREAD

**Issue by inpyeong** [kookmin-sw/capstone-2020-4#11]
텍스트의 모든 형태소를 FastText모델만을 이용하여 검열할 시 오분류할 확률이 높다고 판단됩니다.
정확도를 높이기 위해 기존 음성 검열 방식에 String Matching 알고리즘을 추가하는 것이 어떤가요?

String Matching 알고리즘이 추가된 음성 검열 방식은 다음과 같습니다.

- STT를 이용하여 음성을 텍스트로 변환
- Khaiii를 통해 텍스트 형태소 분석.
- 분석된 형태소와 욕설 리스트 원소 간의 cosine similarity를 FastText 모델을 이용하여 계산.
- cosine similarity가 70% 이상이라면, String Matching을 이용하여 해당 형태소 안에 욕설이 존재하는지 판단.

 comment 남겨주세요.

**Comment by leejuhyoung11** [comment]
cosine similarity 측정 메소드를  유사도 임계값을 기준으로 case 를 두분류로 나누어 string matching 을 실행하는 파트와 실행하지 않는 파트로 구분하였습니다. 

- 욕설과 함께 주로 사용되는 형태소에 한해 string matching 이 진행됩니다.
