### ISSUE TITLE
khaiii 동작 관련 이슈

### ISSUE THREAD

**Issue by leejuhyoung11** [kookmin-sw/capstone-2020-4#13]
api = KhaiiiApi('/usr/local/lib/libkhaiii.so','/usr/local/lib/python3.5/dist-packages/khaiii/share/khaiii')

khaiii 라이브러리 가 설치된 디렉토리 밖에서 이를 호출 시  libkhaiii.so 를 찾을 수 없습니다.

**Comment by inpyeong** [comment]
python3 가 설치된 디렉토리 내부의 libkhaiii.so를 호출해야 합니다.

/usr/lib/python3.5/dist-packages/khaiii/lib/libkhaiii.so 로 경로 지정 후 다시 실행해보십시오.
