### ISSUE TITLE
Knife label 검열에 대한 정확도

### ISSUE THREAD

**Issue by inpyeong** [kookmin-sw/capstone-2020-4#16]
현재 Knife Label에 대한 영상 검열이 정확하지 않습니다. 이에 대한 제 의견입니다.

 - Knife Label의 데이터셋에는 너무나도 다양한 동작들이 존재하여 모델이 특징점을 찾기 어렵습니다.

 - Optical Flow Dataset에서는 칼에 찔린 장면과 단순한 칼 싸움 장면이 거의 동일하게 묘사됩니다.

Knife Label 검열 정확도를 향상시키기 위해 다음과 같이 진행하였습니다.
 - 칼로 베는 장면이 아닌 찌르는 장면으로만 데이터셋이 구성되도록 했습니다. 
 - 기존 UCF101 Optical Flow Dataset이 각 프레임에 대한 motion을 정확히 반영하지 못했기 때문에  UCF101 Dataset에 대한 Optical Flow을 다시 추출하였습니다.

정확도 향상을 위한 또 다른 방안이 있다면 comment로 남겨주시기 바랍니다.

**Comment by xogns7868** [comment]
몇 프레임을 관찰하여 결정하는 시점도 굉장히 중요하다고 생각됩니다. 현재 10프레임을 관찰하고 무슨 동작인지 예측하는데, 다양한 프레임 시점을 실험해서 최적의 값을 찾아야할 것 같습니다. 또한 UCF101 데이터셋이 비해 Knife에 해당되는 데이터셋이 조금 상이하다보니 공개되어있는 여러 데이터셋을 추가하는 것도 고려해봐야될 것 같습니다.

**Comment by inpyeong** [comment]
comment 감사합니다. 
말씀하신대로 공개되어 있는 여러 데이터셋 추가를 고려해보도록 하겠습니다.

현재 진행 상황입니다.
- 자체적으로 구축한 UCF101 Optical Flow Dataset를 이용한 결과 Knife label에 대한 Temporal stream ConvNet 모델의 성능이 매우 향상되었습니다. 
- 모델이 Knife label에 대한 특징점을 명확히 파악할 수 있도록 Knife dataset에서 여러 가지 동작을 갖는 data를 제외하였습니다.

**Comment by inpyeong** [comment]
Knife label뿐만 아니라 전체적인 검열의 정확도를 향상시키기 위해 꾸준히 자체적으로 테스트를 진행하고 있습니다.

앞으로 도출되는 결과들은 milestone-3에서 다루도록 하겠습니다. issue close하겠습니다.
