### ISSUE TITLE
기술 설명을 위한 페이지 추가 개발

### ISSUE THREAD

**Issue by Sungsoo-FE** [kookmin-sw/capstone-2020-4#18]
웹 페이지에 저희 프로젝트의 기술에 대해 설명해주는 페이지를 추가 개발하고자 합니다.

어떤식으로 페이지를 구성하고 어떤 내용을 설명할 것인지 답글 달아 주시면 감사하겠습니다.

**Comment by inpyeong** [comment]
다음과 같은 내용들로 페이지를 구성하면 어떨까요?
- 프로젝트의 전체적인 흐름도
- AWS Instance에  영상이 업로드되는 과정
    - 소켓 통신
- 영상 검열
    - 사용되는 기술스택 설명 
    - 영상 검열 모델 학습에 대한 내용
    - 영상 검열 흐름도
- 음성 검열
    - 사용되는 기술스택 설명
    - 음성 검열 모델 학습에 대한 내용
    - 음성 검열 흐름도
- 검열에 대한 정확도

혹시 수정 또는 추가해야 할 내용이 있다면 comment 남겨주세요.
