### ISSUE TITLE
음성 필터링 수정 사항 및 적용 사항 

### ISSUE THREAD

**Issue by leejuhyoung11** [kookmin-sw/capstone-2020-4#19]
음성 필터링 과정이 다음과 같이 수정되었습니다. 

- 비속어 필터링 과정 중 코사인 유사도를 계산할 떄 사용하는 욕설 리스트를 문자열 매칭 함수로 이동시켰습니다. (기존 욕설리스트는 문자열 매칭 시 사용되며 코사인 유사도 계산 시에는 욕설 리스트를 사용하지 않습니다.)

- 최종 출력 파일을 수정된 음성 파일과 검열된 텍스트 데이터로 구분지었습니다. ( 텍스트 데이터에는 발화된 욕설과 발화 시간이 포함됩니다.)

**Comment by inpyeong** [comment]
코사인 유사도 계산 시 욕설 리스트를 사용하지 않는다는 내용은 대표적인 욕설 하나만을 고려한다는 것인가요? 만약 그렇다면 어떤 욕설을 고려하셨나요?

**Comment by leejuhyoung11** [comment]
초기 모델링 단계에서 사용하였던 욕설을 사용하여 유사도를 계산하였습니다. 
voice_filter.py 를 참고해주세요
