### ISSUE TITLE
영상 필터링을 위한 시스템 설계

### ISSUE THREAD

**Issue by xogns7868** [kookmin-sw/capstone-2020-4#2]
영상 필터링을 위해 프레임을 추출하고, 딥러닝 모델에 넣어 필터링 하는 것 까지의 과정을 클래스 다이어그램으로 설계합니다.
일련의 과정은 다음과 같습니다.
 - 유저가 영상을 업로드 합니다.
 - 업로드된 영상의 길이를 파악하고, 3초 간격으로 프레임을 추출해 각 폴더에 저장 
    합니다.
 - 각 폴더가 하나의 영상 데이터가 되며, 딥러닝 모델의 인풋 데이터로 들어갑니다.
 - 필터링이 완료되면 썸네일 프레임과 구간 내용을 기록합니다.

**Comment by inpyeong** [comment]
위의 과정에 따라 설계한 class diagram입니다.

![Class_Diagram](https://user-images.githubusercontent.com/58331907/77146645-e0782980-6ace-11ea-9d07-466249ebae80.PNG)

각 클래스에 선언된  메소드에 대한 설명입니다.

 - User 
   - uploadVideo : 영상을 업로드                        
 - Video_handler
   - checkUpload : 영상 업로드의 성공 유무를 판단.
   - checkVideoLength : 업로드된 영상의 길이 리턴.
   - senInterval : 영상의 길이를 3초 간격으로 나눈 시간들을 배열에  순차적으로 저장.
   - sendFrame : Filter Class에 추출된 프레임을 전송.
 - Frame
   - cutFrame : 영상으로부터 프레임을 추출.
   - saveFrameinFolder : 지정된 폴더에 프레임 저장.
   - createFolder : 프레임을 저장할 폴더 생성.
 - Filter
   - Tagging : 구간을 태깅.
   - sendResult : 태깅 결과를 전송.

Class Diagram을 설계하는 과정에서 동영상의 길이가 길다면 많은 폴더와 프레임들이 생성되기 때문에 적지 않은 저장 공간을 차지할 것으로 예상되었습니다. 이에 따른 개선 방안이 있다면 comment 남겨주시기 바랍니다.


또한 추가적인 변경 사항과 개선 방안이 있다면 알려주십시오.

**Comment by xogns7868** [comment]
그렇다면 프레임 추출시 temp 폴더를 생성하고, 해당 폴더에 구간에 따른 프레임들을 임시 저장하였다가, 해당 구간의 태깅이 완료된다면 폴더 내에 프레임들을 모두 삭제하고 그 다음 구간을 다시 프레임 추출해서 저장하는 식으로 한다면 어느 정도 해결될 것 같습니다. 하지만 이렇게 진행한다면 부적합한 구간 발견시 프레임들을 삭제해버리기 때문에 구간과 태깅 결과를 저장해놓아야 될 것  같습니다.

그리고 sendResult() 메소드가 현재 썸네일 사진 및 구간 정보를 전달하는 걸로 초기 설정되어있는데, 썸네일이 아닌 프레임들을 뭉쳐서 GIF파일이나 부분 영상 파일로 보내는 것이 어떻습니까?

**Comment by inpyeong** [comment]
comment 감사합니다.

말씀해주신 개선방안 적용하여 다시 Class Diagram 설계하였습니다.

![캡처](https://user-images.githubusercontent.com/58331907/77333710-2e0ec380-6d67-11ea-991a-25dc01513432.PNG)

예전 Class diagram으로부터 추가, 삭제된 각 Class의 method 요약설명입니다.
 - Video_handler
   - sendFrame : Frame_handler와 Filter의 객체가 temp 폴더를 공유하기 때문에 삭제. 
 - Cuttor
   - saveFrameinFolder, createFolder : 각 구간의 프레임을 다른 폴더에 저장하는 것이 아닌 temp 폴더에 저장한 후 검열하기 때문에 삭제.
 - Frame_handler 
   - createTempFolder : temp 폴더 생성.
   - saveFramesInTemp : temp 폴더 안에 프레임 저장.
   - setFrameName : temp 폴더에 프레임 저장 전 호출되어 각 프레임 이름을 구간 정보로 설정.
 - Filter
   - getFrames : temp 폴더로부터 프레임을 가져옴.
   - chooseThumbnail : 각 구간의 프레임 중에서 thumbnail 를 선택.
   - AddLabelToThumbnail : thumbnail의 이름에 Tagging의 결과를 추가.
   - deleteFrames : temp 폴더에 존재하는 프레임 삭제.


System flow는 다음과 같습니다.
1. User가 uploadVideo 호출, Video_handler에게 video file 전달.
2. Video_handler는 setInterval 호출, 프레임 추출 구간 설정.
   Cutter 객체의 cutFrame 호출, 프레임 추출 후 Frame_handler에게 전달.
3. Frame_handler가 createTempFolder 호출, temp 폴더 생성.
4. Frame_handler의  saveFramesInTemp 과정에서 setFrameName 을 호출, 즉 프레임의 이름을 구간 정보로 설정하여 temp 폴더에 저장.
5. Filter가 getFrame 호출, temp 폴더의 프레임을 가져옴.
6. Filter가 Tagging을 호출, 검열 내용이 존재한다면 chooseThumbnail과 AddLabelToThumbnail로 프레임 중 thumbnail 파일을 선택 후 tagging 정보를 파일 이름에 저장. 
7. 위의 과정을 거쳤거나 검열 내용이 없을 경우 deleteFrames 호출, temp 폴더에 존재하는 프레임 삭제. 
8. Filter가 sendResult 호출, 결과 전송.

개선 방안 중 GIF에 관한 내용이 있었는데, 결과 전송 시간이 지체될 수 있고 따로 필요성을 느끼지 못하여 이를 반영하지 않았습니다.

**Comment by xogns7868** [comment]
영상 필터링 시스템 설계가 끝났으므로 closed 하겠습니다.
