### ISSUE TITLE
Instance Segmentation 추가

### ISSUE THREAD

**Issue by xogns7868** [kookmin-sw/capstone-2020-4#20]
기존 Object Detection에서 Knife와 Smoke, Adult에 해당하는 카테고리에 대해 Detection의 성능이 많이 좋지 않다는 사실을 파악했습니다. 따라서 Instance Segmentation으로 Knife, Smoke, Gun을 Detection하고 Adult와 게임에서 피를 흘리는 사람의 장면인 Blood라는 라벨을 추가해 Object Detection을 수행합니다. 구조도는 다음과 같습니다.
![image](https://user-images.githubusercontent.com/43363576/82152556-063a6880-989d-11ea-9086-3242ed675970.png)
  
Knife와 Smoke 그리고 Gun 중 아무것도 Detection 되지 않은 사진들은 모두 Object Detection을 통해 Adult인지 아닌지 판단합니다.

또한 Gun이 탐지된 사진들은 Object Detection을 통해 Blood인지 아닌지 판단합니다.

**Comment by xogns7868** [comment]
다음 사진들은 각각 Instance Segmentation을 통해 Knife, Smoke, Gun을 Detect한 결과 화면입니다.

![KakaoTalk_20200518_002155181](https://user-images.githubusercontent.com/43363576/82152659-ca53d300-989d-11ea-9fa5-fa24d5e519a5.png)
![KakaoTalk_20200518_002215264](https://user-images.githubusercontent.com/43363576/82152658-c9bb3c80-989d-11ea-9eee-cd4e4ee71fa8.png)
![KakaoTalk_20200518_002255544](https://user-images.githubusercontent.com/43363576/82152656-c627b580-989d-11ea-9c99-610e0db1d615.png)

**Comment by inpyeong** [comment]
추가된 Instance Segmentation에서 다음과 같은 수정사항이 있었습니다.
- Adult label을 Object Detection이 아닌 Instance Segmentation을 통해 검열
    - Knife와 Smoke 그리고 Gun 중 아무것도 Detection 되지 않은 사진 모두 Object Detection을 통해 Adult label에 대한 검열을 진행하기에 큰 무리가 있다고 판단
- Adult label와 Blood label에 대해 Image Classification을 통한 검열을 추가
    - 보다 정확한 검열을 위해 Image Classification을 도입

구조도는 다음과 같이 수정되었습니다.
![캡처](https://user-images.githubusercontent.com/58331907/82227487-ca69d680-9962-11ea-8e0a-87ec8c8e3b53.PNG)

**Comment by xogns7868** [comment]
네 해당 사항 반영하겠습니다. 이슈 닫겠습니다.
