### ISSUE TITLE
모듈 별 branch 병합

### ISSUE THREAD

**Issue by inpyeong** [kookmin-sw/capstone-2020-4#34]
각자 맡은 모듈의 branch를 master branch의 자식 branch인 develop에 모두 병합해주세요.

병합을 완료한 사람은 comment 남겨주시기 바랍니다.

**Comment by xogns7868** [comment]
back-end, video-classification 병합 완료했습니다.
src 폴더에 aws와 video-backend를 생성해 정리해놓았습니다.

**Comment by xogns7868** [comment]
back-end, video-classification, object-detect 모듈 병합 완료했습니다.
src 폴더에 aws 폴더와 video-backend를 생성해 정리해놓았습니다.

**Comment by leejuhyoung11** [comment]
SpeechToText 모듈을 병합 완료하였습니다. 
Text Embedding 모듈은 SpeechToText 모듈에 병합되어 있어 Close 했습니다.

**Comment by inpyeong** [comment]
front-end 병합 완료하였습니다. 모든 모듈이 병합을 완료하였으니 issue를 close하겠습니다.
