### ISSUE TITLE
웹 어플리케이션 설계

### ISSUE THREAD

**Issue by inpyeong** [kookmin-sw/capstone-2020-4#4]
YouHi 프로젝트 서비스는 Web Application 으로 제공됩니다.

따라서 Web Application 에는 다음과 같은 기능들이 필요할 것으로 보입니다.

 - 영상 업로더가 영상을 웹에 업로드할 수 있도록 한다.
 - 영상과 음성의 검열 결과를 각각 확인할 수 있도록 한다.
 - 업로드 영상을 연령 제한 컨텐츠로 설정하면 검열 과정을 거치지 않도록 한다.
 - AWS S3와 연동될 수 있도록 한다.

추가해야 할 기능이 있거나 각 기능에 대해 구체적인 구현방안이 있다면 comment 남겨주십시오.

**Comment by leejuhyoung11** [comment]
- 영상 업로더가 영상을 웹에 업로드할 수 있도록 한다.
   업로드 시 progress bar 등의 기능을 추가하는 기능이 필요할 것 같습니다 
   웹에 영상이 업로드 되면 영상의 썸네일과 파일명 확장자 등을 표시해주면 좋을것 같습니다

**Comment by minjae1030** [comment]
업로더가 필터링 결과에 대해 이의 신청 및 문의을 할 수 있도록 이러한 기능을 만들었으면 좋겠습니다.

**Comment by Sungsoo-FE** [comment]
프론트 단에서 영상을 업로드 하고 다시 aws로 부터 영상을 불러올 때 api 호출을 통해 가져오도록 하면 될 것 같습니다.
컴포넌트 관리의 편의성을 위해 프론트 엔드는 react.js를 사용하여 개발하는게 좋을 것 같습니다.
더 나아가 웹뿐만이 아닌 모바일 기기를 이용하는 사람들을 위해 모바일 버전의 css 또한 추가 개발하는 것이 좋을 것 같습니다.

**Comment by inpyeong** [comment]
모두 comment 감사합니다.

지금까지 제안된 개선방안들을 적용하여 Web Application을 구현하는데 있어 필요한 기능들을 나열해보겠습니다.

 - 영상 업로더가 웹에 영상을 업로드할 수 있도록 한다.
    - Drag and drop, Upload progress bar, 파일명과 확장자 표시.
 - 영상과 음성의 검열 결과를 각각 확인할 수 있도록 한다.
    - 검열 결과에 대한 이의 신청 및 문의 기능. 
 - AWS S3와 연동될 수 있도록 한다.
    - AWS S3와의 연동을 위해 AWS Gateway API 적용.
 - 업로드 영상을 연령 제한 컨텐츠로 설정하면 검열 과정을 거치지 않도록 한다.
 - 컴포넌트 관리의 편의성을 위해 react.js를 사용한다.
 - 웹뿐만 아니라 모바일 버전의 css 를 추가 개발한다.

앞으로 Web App을 구현하는 과정에 있어 문제가 발생하거나 또 다른 개선 방안이 필요한 경우 다시  issue를 등록하도록 하겠습니다. 


issue closed 하겠습니다.

**Comment by inpyeong** [comment]
목표 1차 수정에 따른 변경 사항을 적용하여 아래 기능은 구현하지 않도록 하겠습니다.

 - 업로드 영상을 연령 제한 컨텐츠로 설정하면 검열 과정을 거치지 않도록 한다.

issue close하겠습니다.
