### ISSUE TITLE
목표 1차 수정

### ISSUE THREAD

**Issue by xogns7868** [kookmin-sw/capstone-2020-4#6]
1. 우리의 목표의 문제점 -> 유튜브에 적용시킨다는 목표는 현실적으로 불가능
따라서 다음과 같이 설정:
유튜브나 여러 플랫폼의 현재 영상 정책에 대한 문제점이 있다. 따라서 여러 플랫폼의 이러한 문제점들을 1차적으로 해결시킬 수 있을만큼 기술적,알고리즘적으로 효율적이고 뛰어난 성능을 보이는 시스템을 개발하는 것이다.

2. 영상 플랫폼이나 SNS를 만드는 목표를 설정하지 않은 이유
사실 우리의 시스템은 업로더나 시청자에게 이득되는 것이 아니다.
그래서 우리가 이런 시스템이 적용된 플랫폼들을 만든다고 해서 사람들이 이용하거나 그런 메리트가 없다.
하지만 필요한 기술이다. 왜냐하면 정말 다양한 플랫폼에서 수많은 영상이 나오는데, 그 중 특정 연령층이 시청하지 않아야 하는 영상들이 다수 공개되어있기 때문이다. 따라서 우리는 플랫폼이나 다른 시나리오에 집중하기 보다는, 이것을 사용하는 플랫폼과 이것을 통해 업로드하는 업로더들에게도 서로 상성이 되는 목표로 1차 설정하게 되었다.

**Comment by xogns7868** [comment]
추후 지도교수님과의 피드백을 받고 목표를 수정하거나 발전시킬 예정입니다. 생각나는 목표나 추가해야할 부분이 있다면 코멘트 남겨주십시오.

**Comment by inpyeong** [comment]
다른 사람들에게 검열 시스템의 성능을 확인시켜줄 수 있도록 저희만의 테스트 방식이 필요할 것으로 보입니다. 

각 라벨 당 일정 개수의 영상을 준비하여 검열한 후 검열 시스템의 결과가 올바른 라벨 값인지 확인하여 백분율로 나타내는 것이 어떤가요?

**Comment by xogns7868** [comment]
알겠습니다. 교수님과의 피드백도 동일한 내용으로 전달받았으니, 해결되었다고 간주하고 closed 하겠습니다.
