### ISSUE TITLE
Image classification 적용

### ISSUE THREAD

**Issue by inpyeong** [kookmin-sw/capstone-2020-4#7]
영상 검열 시 Video classification 만 적용하였을때 19세 미만 시청불가 장면이 아님에도 불구하고 검열이 되는 문제가 발생하였습니다.  이를 해결하기 위해서 image classification 를 추가하여  19세 미만 시청불가 장면을 정확하게 검열하도록 하겠습니다.

이에 대한 의견을 comment로 남겨주세요.

**Comment by kwtjdtn** [comment]
nav bar에 저희 팀을 나타낼 수 있는 로고가 들어가면 좋을 것 같습니다. 
다른 기능들은 필요한 경우 그 때 추가하는 것이 좋을 것 같습니다.

**Comment by inpyeong** [comment]
issue close 하겠습니다. 추후 변동 사항이 있다면 reopen하도록 하겠습니다.

**Comment by xogns7868** [comment]
먼저, Image Classification이 적용된 검열 과정부터 설명드리겠습니다.
영상이 5초 단위로 subclip이 추출됩니다. (만약 전체 길이가 1분짜리 영상이면 5초 영상 20개 추출)
그리고 추출된 영상을 Video Classification을 진행해서 고위험군 영상인지 아닌지 판단합니다.
만약 고위험군 영상이 아닌 일반적인 영상이라면 거기서 종료되며, 고위험군 영상으로 분류된 영상은 다음 과정인 Image Classification이 진행됩니다. Image Classification은 19세 미만인지 19세 이상인지 명확하게 판단할 수 있게, 해당 데이터셋만 구축해서 진행될 예정이며, 만약 데이터셋이 모자라거나 정확하지 않다면 추후 논의하는 것으로 하겠습니다.

Image Classification 모델은 ResNet-152 모델을 채택해서 학습시킬 예정이며, 담배, 잔인한 장면으로 정확하게 담배임을 감지하거나, 칼에 찔려서 피가 나는 장면을 감지하는 시스템을 구축할 예정입니다.

**Comment by xogns7868** [comment]
Image Classification 적용 방식이 변경되었습니다. 기존 Image Classfication을 최종 확인으로 사용하려 했으나, 해당 데이터셋을 모으기가 상당히 현실적으로 어렵기 때문에, 고위험군 판단을 Image Classification으로 설정했습니다. 이후 고위험군으로 판단된 구간을 추출하고 Video Classification을 진행하기로 했습니다. 

변경 방식이 fixed 됐으므로, 이슈 closed 하겠습니다.

**Comment by xogns7868** [comment]
Image Classification 적용을 폐기하고, Obejct Detection으로 고위험군 분류를 하기로 결정했습니다. 변경한 사유는 다음과 같습니다.
  - Image Classification을 통해 분류하려면 Negative Dataset과 방대한 양의 Dataset이 필요했습니다.
  - Knife의 경우 너무도 다양한 상황이 연출되어, 제대로 된 특징점을 모델이 학습하기 힘듭니다.

따라서 저희는 Object Detection을 통해, 칼, 담배, 여성, 총에 대한 감지가 이루어지면 고위험군으로 판단하기로 했습니다. 

closed하겠습니다.
