### ISSUE TITLE
Fasttext 모델링과 학습

### ISSUE THREAD

**Issue by inpyeong** [kookmin-sw/capstone-2020-4#8]
욕설 검열을 위한 Fasttext 모델링 및 학습.

**Comment by inpyeong** [comment]
Fasttext 모델링 및 학습에 필요한 데이터를 구축하기 위해 개인 노트북에서 400MB 이상의 corpus를 khaiii로 형태소 분석을 진행하였으나 그 과정에서 메모리가 부족하여 완료하지 못했습니다.


개인 노트북이 아닌 AWS EC2 instance 에서 형태소 분석을 진행하도록 하겠습니다.
또한 형태소 분석 전까지 계속 웹 크롤링을 통해 욕설 데이터를 보강하도록 하겠습니다.

**Comment by xogns7868** [comment]
그런데 욕설 데이터만 크롤링할 경우 일반적인 단어에 대한 유사도를 체크하였을 때 확인 데이터셋이 욕설 밖에 존재하기 때문에, 마찬가지로 욕설과 일반적인 단어의 유사도가 높을 것으로 예상됩니다. 따라서 욕설 데이터 뿐만 아니라 욕설이 들어가있지 않은 일반적인 단어들로 구성되어있는 데이터셋 또한 크롤링 구축이 필요할 것 같습니다.

**Comment by inpyeong** [comment]
comment 감사합니다. 

의견을 수렴하여 데이터 크롤링 시 욕설이 아닌 내용들도 포함하도록 하겠습니다.

**Comment by inpyeong** [comment]
추후에 issue reopen 하도록 하겠습니다.

issue close 하겠습니다.

**Comment by inpyeong** [comment]
형태소 분석은 FastText 학습 데이터가 아닌, 음성 검열의 Test Case에 적용되어야 하기 때문에 메모리 부족 문제 없이 FastText 모델을 Train할 수 있었습니다. 위의 comment에서 제기되었던 문제는 해결되었음을 알리고 다시 issue closed 하겠습니다.
