### ISSUE TITLE
YouHi web page 디자인 초안

### ISSUE THREAD

**Issue by Sungsoo-FE** [kookmin-sw/capstone-2020-4#9]
![YouHi 디자인 초안](https://user-images.githubusercontent.com/43291256/78450800-1bc44c00-76bc-11ea-9b11-375a44029303.jpeg)
YouHi web page 디자인 초안입니다.
혹시 추가 해야 할 기능이나 수정이 필요한 디자인이 있으면 말씀해주세요.

**Comment by inpyeong** [comment]
background image 위에 우리 프로젝트의 이름과 한 줄 정도의 소개글을 추가하는건 어떨까요? 

그리고 필터링 결과를 확인하는 박스 버튼에도 영상과 음성을 나타내는 이미지를 추가하면 좋을 것 같습니다.

**Comment by Sungsoo-FE** [comment]
코멘트 감사합니다. background image에 프로젝트 이름 및 소개글을 추가하도록 하겠습니다
또한 필터링 결과를 확인하는 박스에 각각의 이미지를 추가하고 박스를 클릭했을 때 결과를 볼 수 있도록 하겠습니다.
